### ISSUE TITLE
Attaching any image causes request to fail with `INVALID_ARGUMENT (code 400)` — media part is sent without inline data (Windows)

### ISSUE THREAD

**Issue by Elaina-siki** [google-antigravity/antigravity-cli#755]
## Environment

- OS: Windows 11 Home 23H2 (build 26200), zh-CN locale
- CLI: Antigravity CLI (`agy.exe`) installed via winget (`Google.AntigravityCLI`)
- Language server version: 1.1.10 (from `cli.log`: `Language server version: 1.1.10`)
- Model: default (`Gemini 3.6 Flash (High)`), also fails in print mode

## Summary

Every message that attaches an image (by typing/pasting an image file path as the prompt) fails with `INVALID_ARGUMENT (code 400): Request contains an invalid argument.` The CLI logs `error calculating media token count: media has no inline data` right before the 400. The image is copied correctly to `.tempmediaStorage/media_<ts>.png` (byte-identical to source), but the API request's media part never contains inline data.

## Steps to reproduce

1. Launch agy (interactive), then send an image path as the prompt:
   ```
   D:\temp\pic.png
   ```
2. Or in print mode:
   ```
   agy -p "D:\temp\pic.png describe this image"
   ```
3. The request fails with `Agent execution terminated due to error.` / the 400 error.

## Observed in log (every attempt, deterministic)

```
trajectory_chat_converter.go:622  error calculating media token count: media has no inline data
stream_handler.go:101  error encountered while processing planner output: INVALID_ARGUMENT (code 400): Request contains an invalid argument.
executor.go:525  error in generator: INVALID_ARGUMENT (code 400): Request contains an invalid argument.
```

## KEY FINDING: regression — works in 1.1.9, broken in 1.1.10

- Downgraded to package version **1.1.9** (winget `Google.AntigravityCLI --version 1.1.9`) → images work perfectly, including the Chinese-path 3 MB screenshot above.
- Broken on **1.1.10** (language server 1.1.10).
- This is a regression introduced in 1.1.10, which should help narrow the cause (likely in the media/trajectory request-building refactor).

## Already ruled out (tested)

- **Non-ASCII path** (`D:\图片\截图3\屏幕截图(7562).png`, Chinese chars + parentheses): fails.
- **Pure-ASCII path** (`D:\temp\pic_7562.png`): fails.
- **Working directory on C: drive** (`C:\temp`): fails.
- **File size** (80-byte 16×16 PNG): fails identically.
- **File read failure**: the temp copy at `.tempmediaStorage/media_<ts>.png` is always created and is byte-identical to the source, so the media pipeline can read the file; the failure is at the request-building step, where the inline data is never populated.

## Additional observations

1. **Conversation poisoning**: after one failed image message, *every* subsequent message in the same conversation — even plain text — fails with the same 400, because history replay includes the media item without inline data. Only starting a new conversation (or `/clear`) recovers.
2. **Related Windows path bug**: logs repeatedly show
   `open /Users/Ciao/.gemini/antigravity-cli/brain/<id>/.system_generated/logs/transcript.jsonl: The system cannot find the path specified.`
   `/Users/<user>/...` is a Unix-style absolute path; on Windows it resolves relative to the current drive, so it only works when the CWD is on `C:`. This suggests home-dir resolution is hardcoded/Unix-style instead of using `os.UserHomeDir()` + `filepath.Join` on Windows.
3. The stored media item contains a URL-encoded `file:///` URI and a local temp path, but the trajectory→chat converter never reads the file to populate `inline_data`.

## Expected behavior

Image should be attached and visible to the model (as it presumably works on macOS/Linux).

## Suggested fix direction

- In `trajectory_chat_converter`, when building the request for a media item that has no inline data, load the bytes from the temp copy path (`.tempmediaStorage/media_*.png`) or the source `file:///` URI, and populate the media Part's inline data.
- Replace hardcoded `/Users/<user>` path construction with `os.UserHomeDir()`/`filepath.Join` for Windows.
